/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ArtifactId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const Artifact = IDL.Record({
  'id' : ArtifactId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'earnedAt' : Timestamp,
});
export const NpcId = IDL.Nat;
export const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
export const ZoneId = IDL.Nat;
export const Npc = IDL.Record({
  'id' : NpcId,
  'name' : IDL.Text,
  'dialogue' : IDL.Vec(IDL.Text),
  'position' : Position,
  'zoneId' : ZoneId,
});
export const PlayerId = IDL.Principal;
export const QuestId = IDL.Nat;
export const QuestStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const WaypointId = IDL.Nat;
export const Quest = IDL.Record({
  'id' : QuestId,
  'status' : QuestStatus,
  'title' : IDL.Text,
  'observedWaypoints' : IDL.Vec(WaypointId),
  'description' : IDL.Text,
  'giverNpcId' : NpcId,
  'requiredWaypoints' : IDL.Vec(WaypointId),
  'zoneId' : ZoneId,
});
export const PlayerState = IDL.Record({
  'principal' : PlayerId,
  'activeQuests' : IDL.Vec(Quest),
  'artifacts' : IDL.Vec(Artifact),
  'completedQuestIds' : IDL.Vec(QuestId),
  'position' : Position,
  'currentZoneId' : ZoneId,
});
export const Waypoint = IDL.Record({
  'id' : WaypointId,
  'observed' : IDL.Bool,
  'waypointLabel' : IDL.Text,
  'position' : Position,
  'zoneId' : ZoneId,
});
export const Zone = IDL.Record({
  'id' : ZoneId,
  'height' : IDL.Nat,
  'name' : IDL.Text,
  'width' : IDL.Nat,
});

export const idlService = IDL.Service({
  '__artifacts' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Artifact)],
      ['query'],
    ),
  '__npcs' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Npc)],
      ['query'],
    ),
  '__playerStates' : IDL.Func(
      [IDL.Opt(PlayerId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(PlayerId, PlayerState))],
      ['query'],
    ),
  '__quests' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Quest)],
      ['query'],
    ),
  '__waypoints' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Waypoint)],
      ['query'],
    ),
  '__zones' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Zone)],
      ['query'],
    ),
  'completeQuest' : IDL.Func([QuestId], [IDL.Opt(Artifact)], []),
  'getArtifactsForPlayer' : IDL.Func([], [IDL.Vec(Artifact)], []),
  'getNpc' : IDL.Func([NpcId], [IDL.Opt(Npc)], ['query']),
  'getNpcsInZone' : IDL.Func([ZoneId], [IDL.Vec(Npc)], ['query']),
  'getPlayerState' : IDL.Func([], [IDL.Opt(PlayerState)], []),
  'getQuest' : IDL.Func([QuestId], [IDL.Opt(Quest)], ['query']),
  'getQuestsForPlayer' : IDL.Func([], [IDL.Vec(Quest)], []),
  'getWaypointsInZone' : IDL.Func([ZoneId], [IDL.Vec(Waypoint)], ['query']),
  'getZone' : IDL.Func([ZoneId], [IDL.Opt(Zone)], ['query']),
  'getZones' : IDL.Func([], [IDL.Vec(Zone)], ['query']),
  'initPlayerState' : IDL.Func([], [PlayerState], []),
  'observeWaypoint' : IDL.Func([WaypointId], [Quest], []),
  'startQuest' : IDL.Func([QuestId], [Quest], []),
  'updatePlayerPosition' : IDL.Func([ZoneId, Position], [PlayerState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ArtifactId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const Artifact = IDL.Record({
    'id' : ArtifactId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'earnedAt' : Timestamp,
  });
  const NpcId = IDL.Nat;
  const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
  const ZoneId = IDL.Nat;
  const Npc = IDL.Record({
    'id' : NpcId,
    'name' : IDL.Text,
    'dialogue' : IDL.Vec(IDL.Text),
    'position' : Position,
    'zoneId' : ZoneId,
  });
  const PlayerId = IDL.Principal;
  const QuestId = IDL.Nat;
  const QuestStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const WaypointId = IDL.Nat;
  const Quest = IDL.Record({
    'id' : QuestId,
    'status' : QuestStatus,
    'title' : IDL.Text,
    'observedWaypoints' : IDL.Vec(WaypointId),
    'description' : IDL.Text,
    'giverNpcId' : NpcId,
    'requiredWaypoints' : IDL.Vec(WaypointId),
    'zoneId' : ZoneId,
  });
  const PlayerState = IDL.Record({
    'principal' : PlayerId,
    'activeQuests' : IDL.Vec(Quest),
    'artifacts' : IDL.Vec(Artifact),
    'completedQuestIds' : IDL.Vec(QuestId),
    'position' : Position,
    'currentZoneId' : ZoneId,
  });
  const Waypoint = IDL.Record({
    'id' : WaypointId,
    'observed' : IDL.Bool,
    'waypointLabel' : IDL.Text,
    'position' : Position,
    'zoneId' : ZoneId,
  });
  const Zone = IDL.Record({
    'id' : ZoneId,
    'height' : IDL.Nat,
    'name' : IDL.Text,
    'width' : IDL.Nat,
  });
  
  return IDL.Service({
    '__artifacts' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Artifact)],
        ['query'],
      ),
    '__npcs' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Npc)],
        ['query'],
      ),
    '__playerStates' : IDL.Func(
        [IDL.Opt(PlayerId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(PlayerId, PlayerState))],
        ['query'],
      ),
    '__quests' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Quest)],
        ['query'],
      ),
    '__waypoints' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Waypoint)],
        ['query'],
      ),
    '__zones' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Zone)],
        ['query'],
      ),
    'completeQuest' : IDL.Func([QuestId], [IDL.Opt(Artifact)], []),
    'getArtifactsForPlayer' : IDL.Func([], [IDL.Vec(Artifact)], []),
    'getNpc' : IDL.Func([NpcId], [IDL.Opt(Npc)], ['query']),
    'getNpcsInZone' : IDL.Func([ZoneId], [IDL.Vec(Npc)], ['query']),
    'getPlayerState' : IDL.Func([], [IDL.Opt(PlayerState)], []),
    'getQuest' : IDL.Func([QuestId], [IDL.Opt(Quest)], ['query']),
    'getQuestsForPlayer' : IDL.Func([], [IDL.Vec(Quest)], []),
    'getWaypointsInZone' : IDL.Func([ZoneId], [IDL.Vec(Waypoint)], ['query']),
    'getZone' : IDL.Func([ZoneId], [IDL.Opt(Zone)], ['query']),
    'getZones' : IDL.Func([], [IDL.Vec(Zone)], ['query']),
    'initPlayerState' : IDL.Func([], [PlayerState], []),
    'observeWaypoint' : IDL.Func([WaypointId], [Quest], []),
    'startQuest' : IDL.Func([QuestId], [Quest], []),
    'updatePlayerPosition' : IDL.Func([ZoneId, Position], [PlayerState], []),
  });
};

export const init = ({ IDL }) => { return []; };