/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artifact {
  'id' : ArtifactId,
  'title' : string,
  'description' : string,
  'earnedAt' : Timestamp,
}
export type ArtifactId = bigint;
export interface Npc {
  'id' : NpcId,
  'name' : string,
  'dialogue' : Array<string>,
  'position' : Position,
  'zoneId' : ZoneId,
}
export type NpcId = bigint;
export type PlayerId = Principal;
export interface PlayerState {
  'principal' : PlayerId,
  'activeQuests' : Array<Quest>,
  'artifacts' : Array<Artifact>,
  'completedQuestIds' : Array<QuestId>,
  'position' : Position,
  'currentZoneId' : ZoneId,
}
export interface Position { 'x' : bigint, 'y' : bigint }
export interface Quest {
  'id' : QuestId,
  'status' : QuestStatus,
  'title' : string,
  'observedWaypoints' : Array<WaypointId>,
  'description' : string,
  'giverNpcId' : NpcId,
  'requiredWaypoints' : Array<WaypointId>,
  'zoneId' : ZoneId,
}
export type QuestId = bigint;
export type QuestStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export interface Waypoint {
  'id' : WaypointId,
  'observed' : boolean,
  'waypointLabel' : string,
  'position' : Position,
  'zoneId' : ZoneId,
}
export type WaypointId = bigint;
export interface Zone {
  'id' : ZoneId,
  'height' : bigint,
  'name' : string,
  'width' : bigint,
}
export type ZoneId = bigint;
export interface _SERVICE {
  '__artifacts' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Artifact>>,
  '__npcs' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Npc>>,
  '__playerStates' : ActorMethod<
    [[] | [PlayerId], [] | [bigint]],
    Array<[PlayerId, PlayerState]>
  >,
  '__quests' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Quest>>,
  '__waypoints' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Waypoint>>,
  '__zones' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Zone>>,
  'completeQuest' : ActorMethod<[QuestId], [] | [Artifact]>,
  'getArtifactsForPlayer' : ActorMethod<[], Array<Artifact>>,
  'getNpc' : ActorMethod<[NpcId], [] | [Npc]>,
  'getNpcsInZone' : ActorMethod<[ZoneId], Array<Npc>>,
  'getPlayerState' : ActorMethod<[], [] | [PlayerState]>,
  'getQuest' : ActorMethod<[QuestId], [] | [Quest]>,
  'getQuestsForPlayer' : ActorMethod<[], Array<Quest>>,
  'getWaypointsInZone' : ActorMethod<[ZoneId], Array<Waypoint>>,
  'getZone' : ActorMethod<[ZoneId], [] | [Zone]>,
  'getZones' : ActorMethod<[], Array<Zone>>,
  'initPlayerState' : ActorMethod<[], PlayerState>,
  'observeWaypoint' : ActorMethod<[WaypointId], Quest>,
  'startQuest' : ActorMethod<[QuestId], Quest>,
  'updatePlayerPosition' : ActorMethod<[ZoneId, Position], PlayerState>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];