/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type QuestId = bigint;
export interface Zone {
    id: ZoneId;
    height: bigint;
    name: string;
    width: bigint;
}
export type Timestamp = bigint;
export interface Artifact {
    id: ArtifactId;
    title: string;
    description: string;
    earnedAt: Timestamp;
}
export type NpcId = bigint;
export type ZoneId = bigint;
export interface Waypoint {
    id: WaypointId;
    observed: boolean;
    waypointLabel: string;
    position: Position;
    zoneId: ZoneId;
}
export type PlayerId = Principal;
export interface Position {
    x: bigint;
    y: bigint;
}
export interface PlayerState {
    principal: PlayerId;
    activeQuests: Array<Quest>;
    artifacts: Array<Artifact>;
    completedQuestIds: Array<QuestId>;
    position: Position;
    currentZoneId: ZoneId;
}
export interface Quest {
    id: QuestId;
    status: QuestStatus;
    title: string;
    observedWaypoints: Array<WaypointId>;
    description: string;
    giverNpcId: NpcId;
    requiredWaypoints: Array<WaypointId>;
    zoneId: ZoneId;
}
export interface Npc {
    id: NpcId;
    name: string;
    dialogue: Array<string>;
    position: Position;
    zoneId: ZoneId;
}
export type WaypointId = bigint;
export type ArtifactId = bigint;
export enum QuestStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    __artifacts(io: bigint | null, count: bigint | null): Promise<Array<Artifact>>;
    __npcs(io: bigint | null, count: bigint | null): Promise<Array<Npc>>;
    __playerStates(ko: PlayerId | null, count: bigint | null): Promise<Array<[PlayerId, PlayerState]>>;
    __quests(io: bigint | null, count: bigint | null): Promise<Array<Quest>>;
    __waypoints(io: bigint | null, count: bigint | null): Promise<Array<Waypoint>>;
    __zones(io: bigint | null, count: bigint | null): Promise<Array<Zone>>;
    completeQuest(questId: QuestId): Promise<Artifact | null>;
    getArtifactsForPlayer(): Promise<Array<Artifact>>;
    getNpc(id: NpcId): Promise<Npc | null>;
    getNpcsInZone(zoneId: ZoneId): Promise<Array<Npc>>;
    getPlayerState(): Promise<PlayerState | null>;
    getQuest(id: QuestId): Promise<Quest | null>;
    getQuestsForPlayer(): Promise<Array<Quest>>;
    getWaypointsInZone(zoneId: ZoneId): Promise<Array<Waypoint>>;
    getZone(id: ZoneId): Promise<Zone | null>;
    getZones(): Promise<Array<Zone>>;
    initPlayerState(): Promise<PlayerState>;
    observeWaypoint(waypointId: WaypointId): Promise<Quest>;
    startQuest(questId: QuestId): Promise<Quest>;
    updatePlayerPosition(zoneId: ZoneId, position: Position): Promise<PlayerState>;
}
import type { Artifact as _Artifact, Npc as _Npc, NpcId as _NpcId, PlayerId as _PlayerId, PlayerState as _PlayerState, Position as _Position, Quest as _Quest, QuestId as _QuestId, QuestStatus as _QuestStatus, WaypointId as _WaypointId, Zone as _Zone, ZoneId as _ZoneId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __artifacts(arg0: bigint | null, arg1: bigint | null): Promise<Array<Artifact>> {
        if (this.processError) {
            try {
                const result = await this.actor.__artifacts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__artifacts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __npcs(arg0: bigint | null, arg1: bigint | null): Promise<Array<Npc>> {
        if (this.processError) {
            try {
                const result = await this.actor.__npcs(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__npcs(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __playerStates(arg0: PlayerId | null, arg1: bigint | null): Promise<Array<[PlayerId, PlayerState]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__playerStates(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__playerStates(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __quests(arg0: bigint | null, arg1: bigint | null): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.__quests(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__quests(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async __waypoints(arg0: bigint | null, arg1: bigint | null): Promise<Array<Waypoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.__waypoints(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__waypoints(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __zones(arg0: bigint | null, arg1: bigint | null): Promise<Array<Zone>> {
        if (this.processError) {
            try {
                const result = await this.actor.__zones(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__zones(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeQuest(arg0: QuestId): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeQuest(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeQuest(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtifactsForPlayer(): Promise<Array<Artifact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtifactsForPlayer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtifactsForPlayer();
            return result;
        }
    }
    async getNpc(arg0: NpcId): Promise<Npc | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNpc(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNpc(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNpcsInZone(arg0: ZoneId): Promise<Array<Npc>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNpcsInZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNpcsInZone(arg0);
            return result;
        }
    }
    async getPlayerState(): Promise<PlayerState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerState();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerState();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuest(arg0: QuestId): Promise<Quest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuest(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuest(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestsForPlayer(): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestsForPlayer();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestsForPlayer();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaypointsInZone(arg0: ZoneId): Promise<Array<Waypoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaypointsInZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaypointsInZone(arg0);
            return result;
        }
    }
    async getZone(arg0: ZoneId): Promise<Zone | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getZone(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZone(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZones(): Promise<Array<Zone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZones();
            return result;
        }
    }
    async initPlayerState(): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.initPlayerState();
                return from_candid_PlayerState_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initPlayerState();
            return from_candid_PlayerState_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async observeWaypoint(arg0: WaypointId): Promise<Quest> {
        if (this.processError) {
            try {
                const result = await this.actor.observeWaypoint(arg0);
                return from_candid_Quest_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.observeWaypoint(arg0);
            return from_candid_Quest_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async startQuest(arg0: QuestId): Promise<Quest> {
        if (this.processError) {
            try {
                const result = await this.actor.startQuest(arg0);
                return from_candid_Quest_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startQuest(arg0);
            return from_candid_Quest_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlayerPosition(arg0: ZoneId, arg1: Position): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerPosition(arg0, arg1);
                return from_candid_PlayerState_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerPosition(arg0, arg1);
            return from_candid_PlayerState_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PlayerState_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerState): PlayerState {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_QuestStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestStatus): QuestStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Quest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quest): Quest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Artifact]): Artifact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Npc]): Npc | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerState]): PlayerState | null {
    return value.length === 0 ? null : from_candid_PlayerState_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quest]): Quest | null {
    return value.length === 0 ? null : from_candid_Quest_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Zone]): Zone | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _PlayerId;
    activeQuests: Array<_Quest>;
    artifacts: Array<_Artifact>;
    completedQuestIds: Array<_QuestId>;
    position: _Position;
    currentZoneId: _ZoneId;
}): {
    principal: PlayerId;
    activeQuests: Array<Quest>;
    artifacts: Array<Artifact>;
    completedQuestIds: Array<QuestId>;
    position: Position;
    currentZoneId: ZoneId;
} {
    return {
        principal: value.principal,
        activeQuests: from_candid_vec_n7(_uploadFile, _downloadFile, value.activeQuests),
        artifacts: value.artifacts,
        completedQuestIds: value.completedQuestIds,
        position: value.position,
        currentZoneId: value.currentZoneId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestId;
    status: _QuestStatus;
    title: string;
    observedWaypoints: Array<_WaypointId>;
    description: string;
    giverNpcId: _NpcId;
    requiredWaypoints: Array<_WaypointId>;
    zoneId: _ZoneId;
}): {
    id: QuestId;
    status: QuestStatus;
    title: string;
    observedWaypoints: Array<WaypointId>;
    description: string;
    giverNpcId: NpcId;
    requiredWaypoints: Array<WaypointId>;
    zoneId: ZoneId;
} {
    return {
        id: value.id,
        status: from_candid_QuestStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        observedWaypoints: value.observedWaypoints,
        description: value.description,
        giverNpcId: value.giverNpcId,
        requiredWaypoints: value.requiredWaypoints,
        zoneId: value.zoneId
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PlayerId, _PlayerState]): [PlayerId, PlayerState] {
    return [
        value[0],
        from_candid_PlayerState_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): QuestStatus {
    return "notStarted" in value ? QuestStatus.notStarted : "completed" in value ? QuestStatus.completed : "inProgress" in value ? QuestStatus.inProgress : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PlayerId, _PlayerState]>): Array<[PlayerId, PlayerState]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quest>): Array<Quest> {
    return value.map((x)=>from_candid_Quest_n8(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerId | null): [] | [_PlayerId] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
